# Site
name: 'Graft'
description: "Graft: the multilingual review of the Claremont Colleges."
logo: 'assets/images/logo.jpeg'
favicon: 'assets/images/favicon.ico'
url: https://graftreview.org
baseurl: ""   # <- empty if the site is at the domain root
disqus: 'Graft'
email: 'jzdj2025@mymail.pomona.edu'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    bowen:
        name:           Bowen Xu
        avatar:         /assets/images/avatars/bowen.jpg
        role:           Co-Editor in Chief
        bio:            "Hi, my name is è®¸åšæ–‡, I "
        email:          bxvg2025@mymail.pomona.edu
        school:         Pomona
        grade:          Freshman
    zena:
        name:           Zena Almeida-Warwin
        avatar:         /assets/images/avatars/zena.jpg
        role:           Co-Editor in Chief
        bio:            "Hi, my name is é‡‘å¨œ. My Two favorite plants to be grafted are hibiscus & lavender"
        email:          "EMAIL"
        school:         "SCHOOL"
        grade:          "GRADE"

    hakuto :
        name:           Hakuto 
        avatar:         /assets/images/avatars/hakuto.jpg
        role:           Co-Editor in Chief
        bio:            "Hi, my name is ä¼¯äºº(Hakuto) å‹æˆ(Tomonari). My Two favorite plants to be grafted are Mint and Orange! "
        email:          "EMAIL"
        school:         "SCHOOL"
        grade:          "GRADE"
    rochelle:
        name:           Rochelle Lu
        avatar:         /assets/images/avatars/rochelle.jpg
        role:           Co-Editor in Chief
        bio:            "Hi, my name is ç›§è‹¥å¤. My Two favorite plants to be grafted are Mandarin orange and lemon"
        email:          "EMAIL"
        school:         "SCHOOL"
        grade:          "GRADE"

    catarina:
        name:           Catarina
        avatar:         /assets/images/avatars/catarina.jpg
        role:           Co-Editor in Chief
        bio:            "Hi, my name is æ–½è¯ºå¦. My Two favorite plants to be grafted are Bamboo, Lotus"
        email:          "EMAIL"
        school:         "SCHOOL"
        grade:          "GRADE"

    ryosuke:
        name:           Ryosuke Oki
        avatar:         /assets/images/avatars/ryosuke.jpg
        role:           Co-Editor in Chief
        bio:            "Hi, my name is å¤§æœ¨é¼ä»‹. My Two favorite plants to be grafted are cherry trees, pine trees"
        email:          "EMAIL"
        school:         "SCHOOL"
        grade:          "GRADE"

    peter:
        name:           Peter Zhang
        avatar:         /assets/images/avatars/peter.jpg
        role:           Co-Editor in Chief
        bio:            "Hi, my name is å¼ ä¸°æµ©. My Two favorite plants to be grafted are Cherry and orange trees ðŸ¤”"
        email:          "EMAIL"
        school:         "SCHOOL"
        grade:          "GRADE"

    daisy:
        name:           Daisy Dong
        avatar:         /assets/images/avatars/daisy.jpg
        role:           Co-Editor in Chief
        bio:            "Hi, my name is è‘£æ€è¨€. My Two favorite plants to be grafted are the apple tree and pear tree"
        email:          "EMAIL"
        school:         "SCHOOL"
        grade:          "GRADE"
    leslie:
        name:           Leslie Tong
        avatar:         /assets/images/avatars/leslie.jpg
        role:           Co-Editor in Chief
        bio:            "Hi, my name is ä½Ÿæ²å¿†. My Two favorite plants to be grafted are magnolia, rose"
        email:          "EMAIL"
        school:         "SCHOOL"
        grade:          "GRADE"
    pj:
        name:           PJ
        avatar:         /assets/images/avatars/pj.jpg
        role:           Co-Editor in Chief
        bio:            "Hi, my name is PJ å¨›é›². My Two favorite plants to be grafted are Mandarin & Bamboo"
        email:          "EMAIL"
        school:         "SCHOOL"
        grade:          "GRADE"
    jinyao:
        name:           Jinyao Zhang DeSandies
        avatar:         /assets/images/avatars/jinyao.jpg
        role:           Co-Editor in Chief
        bio:            "Hi, my name is å¼ é”¦å°§, my two favorite plants to be grafted are bamboos and carrots."
        email:          "EMAIL"
        school:         "Pomona"
        grade:          "Freshman"

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: [ akash ]
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
